---
all:
  hosts:
    sbxmc01:
      ansible_host: 192.168.1.31
      ansible_ssh_user: kevin
      ansible_ssh_private_key_file: ~/.ssh/prox_lab
      # ansible_ssh_common_args: "-o StrictHostKeyChecking=no"