---
- name: Common Configuration
  hosts: all
  become: true
  roles:
  - roles/common

---
- name: Configure Bastion Host
  hosts: PRDBSTN
  become: true
  roles:
  - roles/bastion

---
- name: Deploy Kubernetes Cluster
  hosts: kubernetes
  become: true
  roles:
  - roles/kubernetes